'''
Created on Nov 2, 2010

@author: karmel
'''
from string import strip
from django.db import connection

genes = """Sgk1                                                                                                
Ifrd1                                                                                               
Zc3hav1                                                                                             
Fus                                                                                                 
Ccnl1                                                                                               
Abi1                                                                                                
Plcl2                                                                                               
Zeb2                                                                                                
Nfat5                                                                                               
Hnrnpa2b1                                                                                           
Eif3a                                                                                               
Zfand5                                                                                              
Baiap2                                                                                              
Ddx5                                                                                                
Csde1                                                                                               
Chd4                                                                                                
Tial1                                                                                               
Cdk12                                                                                               
Gnai3                                                                                               
Tra2b                                                                                               
Jak1                                                                                                
Ggnbp2                                                                                              
Prpf38b                                                                                             
Wnk1                                                                                                
Wsb1                                                                                                
P4ha1                                                                                               
Slc30a9                                                                                             
Psmc6                                                                                               
Tmf1                                                                                                
Slc16a10                                                                                            
Acer3                                                                                               
D6Wsu116e                                                                                           
Malt1                                                                                               
Msn                                                                                                 
Fnbp1l                                                                                              
Rtn3                                                                                                
Bclaf1                                                                                              
Rtn3                                                                                                
Cpd                                                                                                 
Pdss2                                                                                               
Prpf40a                                                                                             
Errfi1                                                                                              
Frmd6                                                                                               
Atp6v0a1                                                                                            
Actr3                                                                                               
Dock10                                                                                              
Fam188a                                                                                             
Sp3                                                                                                 
Txnrd1                                                                                              
Sfpq                                                                                                
Vcl                                                                                                 
Ccnt2                                                                                               
Srsf3                                                                                               
Serinc3                                                                                             
Apbb1ip                                                                                             
Chd2                                                                                                
Txnl1                                                                                               
Atp6v1e1                                                                                            
Psen1                                                                                               
Rb1cc1                                                                                              
Atp9b                                                                                               
Fam107b                                                                                             
Pafah1b1                                                                                            
Ate1                                                                                                
Ctnnb1                                                                                              
Adam17                                                                                              
Hif1a                                                                                               
Vps4b                                                                                               
Wasf2                                                                                               
Rsu1                                                                                                
Rtn4                                                                                                
Slc7a8                                                                                              
Ubr1                                                                                                
Arhgap10                                                                                            
Ifnar2                                                                                              
Zbtb11                                                                                              
Golph3                                                                                              
Ifngr1                                                                                              
Tle4                                                                                                
Mapk1                                                                                               
Mtf2                                                                                                
Rnf19b                                                                                              
Camk2d                                                                                              
D19Ertd386e                                                                                         
Srp54a                                                                                              
Agfg1                                                                                               
G3bp1                                                                                               
Srgap2                                                                                              
1190002H23Rik                                                                                       
Ugp2                                                                                                
Skap2                                                                                               
Man1a2                                                                                              
Tcea1                                                                                               
Anxa5                                                                                               
Ctnnb1                                                                                              
Mdm2                                                                                                
Tiparp                                                                                              
Ube3a                                                                                               
Calr                                                                                                
Col4a3bp                                                                                            
Dcun1d5                                                                                             
Epc1                                                                                                
Slc41a2                                                                                             
Srp54c                                                                                              
Zfp655                                                                                              
2610101N10Rik                                                                                       
Ube3a                                                                                               
Slc6a8                                                                                              
Snx13                                                                                               
Dnajb6                                                                                              
Mettl9                                                                                              
Rbm39                                                                                               
Tmem165                                                                                             
Trip11                                                                                              
Usp47                                                                                               
Atp6v1h                                                                                             
Dcaf10                                                                                              
Esyt2                                                                                               
Larp4b                                                                                              
Arih2                                                                                               
Hnrnpc                                                                                              
Rbpj                                                                                                
Ccdc88a                                                                                             
Otud7b                                                                                              
Zfp207                                                                                              
Etnk1                                                                                               
Prpf39                                                                                              
Sgms1                                                                                               
1110057K04Rik                                                                                       
Ankrd13c                                                                                            
Ddah2                                                                                               
Il6st                                                                                               
Mapre2                                                                                              
Tax1bp1                                                                                             
1110057K04Rik                                                                                       
Anapc1                                                                                              
Basp1                                                                                               
Enox2                                                                                               
Nfx1                                                                                                
Rnf111                                                                                              
Tln1                                                                                                
1700020O03Rik                                                                                       
Cpsf6                                                                                               
Crk                                                                                                 
2810474O19Rik                                                                                       
Glg1                                                                                                
Ptpra                                                                                               
Ranbp2                                                                                              
Anxa3                                                                                               
Apaf1                                                                                               
Eif5                                                                                                
Faf2                                                                                                
Mapk1ip1l                                                                                           
Ncor1                                                                                               
Nck1                                                                                                
Ppid                                                                                                
Vrk2                                                                                                
Vti1a                                                                                               
Cox5a                                                                                               
Sirt1                                                                                               
Wars2                                                                                               
Ddx50                                                                                               
Esd                                                                                                 
Glipr1                                                                                              
Sirt1                                                                                               
Faf1                                                                                                
Htt                                                                                                 
Med15                                                                                               
Rbm25                                                                                               
Rbm33                                                                                               
Abhd12                                                                                              
Acap2                                                                                               
Atp2a2                                                                                              
Brp44l                                                                                              
Btaf1                                                                                               
Taf1d                                                                                               
Vav3                                                                                                
Larp4                                                                                               
Rbpj                                                                                                
Clk4                                                                                                
Gosr2                                                                                               
Herc4                                                                                               
2410042D21Rik                                                                                       
Dirc2                                                                                               
Ero1l                                                                                               
Tnip2                                                                                               
Arl8b                                                                                               
Far1                                                                                                
Fem1b                                                                                               
Pcf11                                                                                               
Atp1a1                                                                                              
Btk                                                                                                 
Chst11                                                                                              
Lamp2                                                                                               
Rad23b                                                                                              
Rnf20                                                                                               
Setd5                                                                                               
Snrnp70                                                                                             
Canx                                                                                                
Dera                                                                                                
Fnip2                                                                                               
Pum2                                                                                                
Top1                                                                                                
2310044G17Rik                                                                                       
Ext1                                                                                                
Gls                                                                                                 
Hmgcr                                                                                               
Hnrnpm                                                                                              
Memo1                                                                                               
Mobkl3                                                                                              
Timm23                                                                                              
Cyb5b                                                                                               
Erbb2ip                                                                                             
Fxr1                                                                                                
Heatr5a                                                                                             
Itgb1                                                                                               
Rab3gap2                                                                                            
Rock2                                                                                               
Tmed5                                                                                               
Tnfrsf21                                                                                            
Chuk                                                                                                
Lrrfip2                                                                                             
Met                                                                                                 
Parg                                                                                                
Tra2a                                                                                               
Txndc11                                                                                             
Wac                                                                                                 
Ythdc1                                                                                              
2700078E11Rik                                                                                       
Atad2b                                                                                              
Hnrnph3                                                                                             
Kpna4                                                                                               
Matr3                                                                                               
Rbm6                                                                                                
Tnks2                                                                                               
Tnrc6a                                                                                              
Zfp346                                                                                              
Zswim6                                                                                              
Arl5b                                                                                               
Nrd1                                                                                                
Slc35a3                                                                                             
Taf2                                                                                                
Ylpm1                                                                                               
Zc3h15                                                                                              
Atp11b                                                                                              
Atxn7l1                                                                                             
Ccdc109b                                                                                            
Dbi                                                                                                 
Fbxo11                                                                                              
Pdia3                                                                                               
Samd8                                                                                               
Tcf4                                                                                                
Zfp148                                                                                              
C330019G07Rik                                                                                       
Gbf1                                                                                                
Hsd17b12                                                                                            
Plk4                                                                                                
Ppfibp1                                                                                             
Srxn1                                                                                               
Tbc1d22a                                                                                            
Vipar                                                                                               
Atf1                                                                                                
Atp6v1b2                                                                                            
Cog3                                                                                                
Fbxl3                                                                                               
Fryl                                                                                                
Mphosph8                                                                                            
Tnfaip8                                                                                             
Uba6                                                                                                
Xpo4                                                                                                
Bag3                                                                                                
Cdk18                                                                                               
Gpatch8                                                                                             
Herc1                                                                                               
Lars2                                                                                               
Myo9a                                                                                               
Pum2                                                                                                
Rapgef6                                                                                             
Slc44a1                                                                                             
Vps37a                                                                                              
Zc3h13                                                                                              
Cytsb                                                                                               
Dnajc1                                                                                              
Fam172a                                                                                             
Pik3c2a                                                                                             
Rabep1                                                                                              
Xrcc4                                                                                               
Arhgap6                                                                                             
Fbxo30                                                                                              
Gbe1                                                                                                
Idi1                                                                                                
Phf20                                                                                               
Tmem85                                                                                              
Zfml                                                                                                
Dapp1                                                                                               
Fnbp1                                                                                               
Inppl1                                                                                              
Stx8                                                                                                
Taf3                                                                                                
Tpp2                                                                                                
Zfp438                                                                                              
Cdk6                                                                                                
Exoc6                                                                                               
Itsn2                                                                                               
Osbpl1a                                                                                             
Phkb                                                                                                
Slc20a2                                                                                             
Slc38a6                                                                                             
Vapa                                                                                                
Zdhhc7                                                                                              
AI848100                                                                                            
Asph                                                                                                
Bre                                                                                                 
Capn7                                                                                               
Eea1                                                                                                
Exoc6b                                                                                              
Ifnar1                                                                                              
Rasa3                                                                                               
Rnf169                                                                                              
Rock1                                                                                               
Tpd52                                                                                               
Zc3h11a                                                                                             
Aff4                                                                                                
Agk                                                                                                 
Csnk1a1                                                                                             
Mier1                                                                                               
Tgoln1                                                                                              
Ube2g1                                                                                              
Zcchc7                                                                                              
2410089E03Rik                                                                                       
Ccdc122                                                                                             
Git2                                                                                                
Itch                                                                                                
Lass5                                                                                               
Pafah1b2                                                                                            
Rnf13                                                                                               
Snrnp48                                                                                             
Synj2bp                                                                                             
Add3                                                                                                
Atxn1                                                                                               
Dopey2                                                                                              
Git2                                                                                                
Gpatch2                                                                                             
Ifi30                                                                                               
Igf2r                                                                                               
Kpna1                                                                                               
Mapk6                                                                                               
Nktr                                                                                                
Pikfyve                                                                                             
Pon3                                                                                                
Tmx4                                                                                                
4933407H18Rik                                                                                       
Gabpb2                                                                                              
Limd1                                                                                               
Mapre2                                                                                              
7-Mar
Mdm4                                                                                                
Nsf                                                                                                 
Nt5dc1                                                                                              
Pabpn1                                                                                              
Psmd11                                                                                              
Rhbdd1                                                                                              
Ubac2                                                                                               
8030462N17Rik                                                                                       
Btf3                                                                                                
Cdv3                                                                                                
Ehmt1                                                                                               
Epc2                                                                                                
Hspa9                                                                                               
Map3k2                                                                                              
Ankrd11                                                                                             
BC057079                                                                                            
Chka                                                                                                
Csgalnact2                                                                                          
Cul5                                                                                                
Fbxo30                                                                                              
Hnrnpl                                                                                              
Lmf1                                                                                                
Mib1                                                                                                
Naa50                                                                                               
Tbcd                                                                                                
Uxs1                                                                                                
Zfp516                                                                                              
6330409N04Rik                                                                                       
Abcf1                                                                                               
Atxn10                                                                                              
Capza2                                                                                              
Cd2ap                                                                                               
Dap3                                                                                                
Heatr3                                                                                              
Hibadh                                                                                              
Mtpn                                                                                                
Nmnat3                                                                                              
Pex7                                                                                                
Qk                                                                                                  
Srsf10                                                                                              
6720456H20Rik                                                                                       
Arhgef12                                                                                            
Atl2                                                                                                
Cdk17                                                                                               
Pbrm1                                                                                               
Pgd                                                                                                 
Rap1b                                                                                               
Snx8                                                                                                
Wasl                                                                                                
Zdhhc20                                                                                             
Zmiz1                                                                                               
2310028H24Rik                                                                                       
4932438A13Rik                                                                                       
Atl2                                                                                                
Ern1                                                                                                
Heatr7a                                                                                             
Hexb                                                                                                
Map2k5                                                                                              
Mbnl2                                                                                               
Riok3                                                                                               
Rsph3b                                                                                              
Sh3bgrl                                                                                             
Slc35b3                                                                                             
Snx9                                                                                                
Sumf1                                                                                               
Tasp1                                                                                               
Tmem167                                                                                             
Tnks                                                                                                
Btf3                                                                                                
Cdk13                                                                                               
Cep350                                                                                              
Chordc1                                                                                             
Cyb5r3                                                                                              
Fam133b                                                                                             
Hnrpll                                                                                              
Pde8a                                                                                               
Psmb7                                                                                               
Psme4                                                                                               
Rab2a                                                                                               
Sqle                                                                                                
Taf1                                                                                                
Ythdf3                                                                                              
1700112E06Rik                                                                                       
4921524J17Rik                                                                                       
Adss                                                                                                
Chpf2                                                                                               
Eprs                                                                                                
Hprt                                                                                                
Hsp90b1                                                                                             
Lims1                                                                                               
Lrrk1                                                                                               
Pag1                                                                                                
Ppig                                                                                                
Prkar1a                                                                                             
Srfbp1                                                                                              
Tlk1                                                                                                
1810074P20Rik                                                                                       
Acadl                                                                                               
Arfgef2                                                                                             
Arfip1                                                                                              
Mpp1                                                                                                
Mpp5                                                                                                
Phf20l1                                                                                             
Ptp4a2                                                                                              
Ralgapa2                                                                                            
Rbm12                                                                                               
Rnf128                                                                                              
Spata6                                                                                              
Tab2                                                                                                
Ubxn4                                                                                               
Zfp322a                                                                                             
Acsl3                                                                                               
Brcc3                                                                                               
Ccar1                                                                                               
Crtc3                                                                                               
Dclre1c                                                                                             
Galc                                                                                                
Ogdh                                                                                                
Rab31                                                                                               
Secisbp2l                                                                                           
Smad5                                                                                               
Ube4b                                                                                               
Utp14b                                                                                              
Dyrk1a                                                                                              
Efha1                                                                                               
Enoph1                                                                                              
Fip1l1                                                                                              
Gnb1l                                                                                               
Mtpap                                                                                               
Pms1                                                                                                
Smpdl3a                                                                                             
Tasp1                                                                                               
Usp16                                                                                               
Znrf2                                                                                               
1300002K09Rik                                                                                       
Asxl2                                                                                               
Bptf                                                                                                
D15Ertd621e                                                                                         
Dennd1b                                                                                             
Galns                                                                                               
Lnp                                                                                                 
Nbas                                                                                                
Orc4l                                                                                               
Phka2                                                                                               
Qrich1                                                                                              
Stxbp4                                                                                              
Tlr13                                                                                               
Arid4b                                                                                              
Cdan1                                                                                               
Eif3e                                                                                               
Fbxo42                                                                                              
Frmd4a                                                                                              
Gphn                                                                                                
Grb2                                                                                                
Hspa14                                                                                              
Lrpap1                                                                                              
Odf2                                                                                                
Paip2                                                                                               
Pdpk1                                                                                               
Phc3                                                                                                
Pitpna                                                                                              
Smad5                                                                                               
Ubr3                                                                                                
Wac                                                                                                 
Acat2                                                                                               
Ahcyl1                                                                                              
Atxn3                                                                                               
D930015E06Rik                                                                                       
Etfdh                                                                                               
Fam108c                                                                                             
Fam3a                                                                                               
Hgsnat                                                                                              
Mamld1                                                                                              
Myo1f                                                                                               
Parl                                                                                                
Phf8                                                                                                
Prmt10                                                                                              
Slc16a6                                                                                             
Smg6                                                                                                
Tcea1                                                                                               
Tes                                                                                                 
Usp3                                                                                                
Wdr70                                                                                               
Zfp407                                                                                              
Ccny                                                                                                
Cnot2                                                                                               
Eif4g3                                                                                              
Epb4.1l2                                                                                            
Fggy                                                                                                
Helz                                                                                                
Kdsr                                                                                                
Mlec                                                                                                
Pitpnc1                                                                                             
Plaa                                                                                                
Rab14                                                                                               
Rc3h1                                                                                               
Skil                                                                                                
Vps13a                                                                                              
Zdhhc14                                                                                             
Zkscan3                                                                                             
2610035D17Rik                                                                                       
Akap10                                                                                              
Arhgap17                                                                                            
Csnk1g1                                                                                             
Fam32a                                                                                              
Glcci1                                                                                              
Mast2                                                                                               
Ndfip2                                                                                              
Pacs1                                                                                               
Pam                                                                                                 
Papd5                                                                                               
Plcg2                                                                                               
Refbp2                                                                                              
Wdhd1                                                                                               
Wdr33                                                                                               
Apex2                                                                                               
Clns1a                                                                                              
D030016E14Rik                                                                                       
D630037F22Rik                                                                                       
Eif4b                                                                                               
Kif11                                                                                               
Mcart6                                                                                              
Mon2                                                                                                
Mrps9                                                                                               
Ncoa1                                                                                               
Nrip1                                                                                               
Ppp3cc                                                                                              
Ptk2                                                                                                
Rngtt                                                                                               
Smurf2                                                                                              
Snx12                                                                                               
Snx14                                                                                               
Spcs3                                                                                               
Stag1                                                                                               
Supt3h                                                                                              
Terf1                                                                                               
Uvrag                                                                                               
Zfp106                                                                                              
Zfp445                                                                                              
Zfyve26                                                                                             
4933426M11Rik                                                                                       
Atg10                                                                                               
Copb1                                                                                               
Galnt1                                                                                              
Lipa                                                                                                
Magi3                                                                                               
Oma1                                                                                                
Parn                                                                                                
Polb                                                                                                
Rbm16                                                                                               
Sestd1                                                                                              
Spata5                                                                                              
Stx6                                                                                                
Tdrd3                                                                                               
Tmem5                                                                                               
Zbed4                                                                                               
1110003E01Rik                                                                                       
Clasp2                                                                                              
Dgkd                                                                                                
Dusp12                                                                                              
Gnb1l                                                                                               
Gprasp1                                                                                             
Mfn1                                                                                                
Nedd9                                                                                               
Odf2                                                                                                
Pi4k2b                                                                                              
Ranbp9                                                                                              
Sergef                                                                                              
Tcerg1                                                                                              
Ubtd2                                                                                               
Arl6ip5                                                                                             
Brms1l                                                                                              
C030046E11Rik                                                                                       
Cdk5r1                                                                                              
Cpped1                                                                                              
Exoc4                                                                                               
Fam63b                                                                                              
Fgd6                                                                                                
Idh1                                                                                                
Iws1                                                                                                
Lactb                                                                                               
Metapl1                                                                                             
Mff                                                                                                 
Pign                                                                                                
Ppp3r1                                                                                              
Prmt3                                                                                               
Tpk1                                                                                                
Zwint                                                                                               
4933437F05Rik                                                                                       
Abcd3                                                                                               
Arl15                                                                                               
Arnt                                                                                                
Atg3                                                                                                
Brd4                                                                                                
Chchd3                                                                                              
E330009J07Rik                                                                                       
Fmnl3                                                                                               
Gab2                                                                                                
Gcc2                                                                                                
Layn                                                                                                
Mfhas1                                                                                              
Mycbp2                                                                                              
Park2                                                                                               
Pparg                                                                                               
Ppp1r12b                                                                                            
Shq1                                                                                                
Smchd1                                                                                              
Spag9                                                                                               
Stip1                                                                                               
Tex264                                                                                              
Upf3b                                                                                               
Vps13b                                                                                              
Vps41                                                                                               
2700029M09Rik                                                                                       
Acbd6                                                                                               
Ammecr1                                                                                             
Arfgef1                                                                                             
Arsg                                                                                                
B4galt1                                                                                             
Cdc73                                                                                               
Dmxl1                                                                                               
Fars2                                                                                               
Foxk2                                                                                               
Klhl15                                                                                              
Lyrm4                                                                                               
Pex3                                                                                                
Prim2                                                                                               
Prkch                                                                                               
Pyroxd1                                                                                             
Rffl                                                                                                
Scamp1                                                                                              
Sepsecs                                                                                             
Smap1                                                                                               
Stk17b                                                                                              
Strn3                                                                                               
Tmem164                                                                                             
Tspan5                                                                                              
Ube3c                                                                                               
Zdhhc1                                                                                              
Zmym2                                                                                               
1110028C15Rik                                                                                       
Atp5l                                                                                               
Ccdc157                                                                                             
Ddx26b                                                                                              
Dopey1                                                                                              
Exoc2                                                                                               
Impa1                                                                                               
Lpp                                                                                                 
Lpxn                                                                                                
Mink1                                                                                               
Oxr1                                                                                                
Phka2                                                                                               
Rap1a                                                                                               
Runx1                                                                                               
Scaper                                                                                              
Vps54                                                                                               
4732471J01Rik                                                                                       
Casd1                                                                                               
Chic2                                                                                               
Dstyk                                                                                               
Fam120c                                                                                             
Farsb                                                                                               
Gng12                                                                                               
Inppl1                                                                                              
Ivns1abp                                                                                            
Jarid2                                                                                              
Manba                                                                                               
Mapk8                                                                                               
Mt2                                                                                                 
Npepps                                                                                              
Osbp                                                                                                
Pla2g6                                                                                              
Prps1                                                                                               
Tecpr1                                                                                              
Trappc10                                                                                            
Ube2w                                                                                               
Zmym4                                                                                               
3110070M22Rik                                                                                       
Aak1                                                                                                
Aatf                                                                                                
Adam10                                                                                              
Atp11c                                                                                              
BC023829                                                                                            
Ccnj                                                                                                
Cyld                                                                                                
D5Ertd579e                                                                                          
Dis3l2                                                                                              
Dock2                                                                                               
Fbxl17                                                                                              
Hltf                                                                                                
Lyst                                                                                                
Mafg                                                                                                
Med13l                                                                                              
N4bp2l2                                                                                             
Nup93                                                                                               
Srsf2ip                                                                                             
Trim44                                                                                              
Tspyl2                                                                                              
Ubap2                                                                                               
Zhx3                                                                                                
A630033H20Rik                                                                                       
Aco2                                                                                                
Caprin2                                                                                             
Clec16a                                                                                             
Cstf2                                                                                               
Cstf3                                                                                               
Ddx3y                                                                                               
Dock11                                                                                              
Erp44                                                                                               
Foxo3                                                                                               
Kif13a                                                                                              
Lmbr1                                                                                               
Luzp1                                                                                               
Mcts1                                                                                               
Mrpl13                                                                                              
Ncoa7                                                                                               
Nfyc                                                                                                
Osbpl9                                                                                              
Plekhm3                                                                                             
Sec22a                                                                                              
Senp7                                                                                               
Sgms1                                                                                               
Slc16a6                                                                                             
Stambpl1                                                                                            
Stk3                                                                                                
Tlr4                                                                                                
Tmem55a                                                                                             
Ttc37                                                                                               
Zfp192                                                                                              
Zfp40                                                                                               
Zfp451                                                                                              
C79407                                                                                              
Cbara1                                                                                              
Cnot7                                                                                               
Coil                                                                                                
D10627                                                                                              
Eif2ak4                                                                                             
Elp4                                                                                                
Ing3                                                                                                
Iqck                                                                                                
Lin54                                                                                               
Nr2c2                                                                                               
Nrp1                                                                                                
Osbpl9                                                                                              
Pde4dip                                                                                             
Phip                                                                                                
Slc22a4                                                                                             
Zfp715                                                                                              
1700019E19Rik                                                                                       
5033414D02Rik                                                                                       
Akap9                                                                                               
Antxr2                                                                                              
Araf                                                                                                
Dab2                                                                                                
Dlg1                                                                                                
Fbxw4                                                                                               
Lclat1                                                                                              
Mbtd1                                                                                               
Nln                                                                                                 
Senp6                                                                                               
Sfmbt1                                                                                              
Slc36a4                                                                                             
Spin1                                                                                               
Tom1                                                                                                
Tsc1                                                                                                
Tsnax                                                                                               """
gene_names = map(strip,genes.replace('\r','\n').replace('\n',',').split(','))

query_kegg = """
SELECT kegg.description FROM genome_reference.kegg_pathway kegg
JOIN genome_reference_mm9.sequence_kegg_pathway seq_kegg
ON kegg.id = seq_kegg.kegg_pathway_id
JOIN genome_reference_mm9.sequence_detail det
ON det.sequence_identifier_id = seq_kegg.sequence_identifier_id
WHERE det.gene_name IN (%s)
GROUP BY kegg.description
HAVING COUNT(kegg.description) > 5;
""" % ("'" + "','".join(gene_names) + "'")

connection.close()
cursor = connection.cursor()
cursor.execute(query_kegg)
rows = cursor.fetchall() or [('',)]

print ', '.join(map(strip,zip(*rows)[0]))
#print ", ".join(gene_names)
print len(gene_names)